#!/usr/bin/env just --justfile

compile_worker:
  fvm dart compile js lib/isolate_worker.dart -o web/rpc_isolate_worker.js
#  fvm dart run isolate_manager:generate

build_runner:
  fvm dart run build_runner build --delete-conflicting-outputs